### ISSUE TITLE
Autocorrect module?

### ISSUE THREAD

**Issue by Busata** [Xrayez/godot-anl#20]
On the http://accidentalnoise.sourceforge.net/minecraftworlds.html page, the autocorrect module is used to map ranges to 0..1, by iirc first sampling values to determine ~ min max.

Is this present in this module, or am I missing something?

**Comment by Xrayez** [comment]
This module doesn't expose any of the [old](https://github.com/JTippetts/accidental-noise-library/tree/old) functionality so that piece of documentation is largely outdated in this case. I'm not sure what would be a replacement for `Autocorrect` module in the [new](https://github.com/JTippetts/accidental-noise-library) version. 

It's likely that:
* it's done automatically for you in the new version.
* some other function replaces it.

According to [code documentation](https://github.com/JTippetts/accidental-noise-library/blob/old/Noise/implicitautocorrect.h#L9-L12), it might be that similar functionality can be achieved with some combination of other elemental functions with `scale_offset`?

Either way, I've exposed most of the public API for the new version. If you think it's missing in the new version, you can open the same issue upstream and ask the author himself here:

https://github.com/JTippetts/accidental-noise-library/issues

and I'll expose it in Godot module without much hassle.

**Comment by Busata** [comment]
Ok thanks, don't find anything that looks like it. scale offset scales the output values + offsets them. Autocorrect basically maps a range from source_low/source_high to target_low/target_high but instead of providing the source values, it guesses by sampling the source emitter/noise values.
